services:
    - type: web
      name: crud-nodejs-finance-api
      env: node
      buildCommand: npm ci && npm run build
      startCommand: npm start
      plan: free
      envVars:
          - key: NODE_ENV
            value: production
