POST http://localhost:3333/transaction
Content-Type: application/json

{
    "name" : "energia",
    "value": " 1400",
    "type": "custos",
    "category": "moradia"
}

###

GET http://localhost:3333/transaction?search=energia


### 


GET http://localhost:3333/transaction


### 


PUT http://localhost:3333/transaction/c2c8661d-8a05-41fb-88a7-be87007311d4
Content-Type: application/json

{
    "name": "mercado",
    "value": "120",
    "type": "custos",
    "category": "moradia"
}

###

DELETE http://localhost:3333/transaction/97baf407-3634-471b-855f-fae763cab682